export const FETCH_CUSTOM_SEARCH = 'FETCH_CUSTOM_SEARCH';
export const FETCH_CUSTOM_SEARCH_SUCCESS = 'FETCH_CUSTOM_SEARCH_SUCCESS';
export const FETCH_CUSTOM_SEARCH_FAIL = 'FETCH_CUSTOM_SEARCH_FAIL';

export const SORT_RESULT_BY_AGE = 'SORT_RESULT_BY_AGE';
export const SORT_RESULT_BY_LOCATION = 'SORT_RESULT_BY_LOCATION';
export const SORT_RESULT_BY_POPULARITY = 'SORT_RESULT_BY_POPULARITY';
export const SORT_RESULT_BY_TAG = 'SORT_RESULT_BY_TAG';

export const RESET_SEARCH_PROFILES = 'RESET_SEARCH_PROFILES';
