export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SUBSCRIBE_TO_NOTIF = 'SUBSCRIBE_TO_NOTIF';
export const RESET_ALL_ACTIVE_NOTIFICATIONS = 'RESET_ALL_ACTIVE_NOTIFICATIONS';
