// export const FETCH_SETTINGS = 'FETCH_SETTINGS';
// export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';

export const SET_PROFILE_SETTINGS = 'SET_PROFILE_SETTINGS';
export const SET_SEARCH_PREFERENCES = 'SET_SEARCH_PREFERENCES';
export const SET_ACCOUNT_SETTINGS = 'SET_ACCOUNT_SETTINGS';
export const SET_USER_TAGS = 'SET_USER_TAGS';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';

export const UPDATE_SEARCH_PREF = 'UPDATE_SEARCH_PREF';
export const UPDATE_SEARCH_PREF_SUCCESS = 'UPDATE_SEARCH_PREF_SUCCESS';
export const UPDATE_SEARCH_PREF_FAIL = 'UPDATE_SEARCH_PREF_FAIL';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const UPDATE_ACCOUNT_SETTINGS = 'UPDATE_ACCOUNT_SETTINGS';
export const UPDATE_ACCOUNT_SETTINGS_SUCCESS = 'UPDATE_ACCOUNT_SETTINGS_SUCCESS';
export const UPDATE_ACCOUNT_SETTINGS_FAIL = 'UPDATE_ACCOUNT_SETTINGS_FAIL';

export const CREATE_TAG = 'CREATE_TAG';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_FAIL = 'CREATE_TAG_FAIL';

export const DELETE_TAG = 'DELETE_TAG';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const DELETE_TAG_FAIL = 'DELETE_TAG_FAIL';

export const UPDATE_BIO = 'UPDATE_BIO';
export const UPDATE_BIO_SUCCESS = 'UPDATE_BIO_SUCCESS';
export const UPDATE_BIO_FAIL = 'UPDATE_BIO_FAIL';

export const SET_IMAGES = 'SET_IMAGES';
export const ADD_IMAGE = 'ADD_IMAGE';
export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const ADD_IMAGE_FAIL = 'ADD_IMAGE_FAIL';

export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const REMOVE_IMAGE_SUCCESS = 'REMOVE_IMAGE_SUCCESS';
export const REMOVE_IMAGE_FAIL = 'REMOVE_IMAGE_FAIL';

export const SET_AVATAR = 'SET_AVATAR';
export const SET_AVATAR_SUCCESS = 'SET_AVATAR_SUCCESS';
export const SET_AVATAR_FAIL = 'SET_AVATAR_FAIL';

export const FETCH_CITY_SUGGESTION = 'FETCH_CITY_SUGGESTION';
export const SET_SUGGESTIONS = 'SET_SUGGESTIONS';

export const FETCH_CITY_COORDINATES = 'FETCH_CITY_COORDINATES';
