export const FETCH_USER_PROFILE_INFOS = 'FETCH_USER_PROFILE_INFOS';
export const FETCH_USER_PROFILE_INFOS_SUCCESS = 'FETCH_USER_PROFILE_INFOS_SUCCESS';
export const FETCH_USER_PROFILE_INFOS_FAIL = 'FETCH_USER_PROFILE_INFOS_FAIL';

export const SET_USER_PROFILE_INFOS = 'SET_USER_PROFILE_INFOS';

export const TOGGLE_LIKE = 'TOGGLE_LIKE';
export const TOGGLE_LIKE_SUCCESS = 'TOGGLE_LIKE_SUCCESS';
export const TOGGLE_LIKE_FALSE = 'TOGGLE_LIKE_FALSE';

export const REPORT_USER = 'REPORT_USER';
export const BLOCK_USER = 'BLOCK_USER';

export const MARK_PROFILE_AS_VISITED = 'MARK_PROFILE_AS_VISITED';
export const SET_PROFILE_HAS_LIKE = 'SET_PROFILE_HAS_LIKE';
